name: 'Start Goodmap Backend'
description: 'Starts the Goodmap Flask backend for E2E tests'
inputs:
  config-path:
    description: 'Path to the Goodmap configuration file'
    required: true
  goodmap-path:
    description: 'Path to the Goodmap repository'
    required: true
  working-directory:
    description: 'Working directory to run make command from'
    required: true
  make-target:
    description: 'Make target to run (e.g., run-e2e-env or run-e2e-stress-env)'
    required: true
    default: 'run-e2e-env'
  log-file:
    description: 'Path to store backend logs'
    required: true
  pid-file:
    description: 'Path to store backend PID'
    required: true
  startup-wait-seconds:
    description: 'Seconds to wait for backend to start'
    required: false
    default: '5'

runs:
  using: 'composite'
  steps:
    - name: Start backend
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
        GOODMAP_PATH: ${{ inputs.goodmap-path }}
      run: |
        make ${{ inputs.make-target }} > ${{ inputs.log-file }} 2>&1 &
        echo $! > ${{ inputs.pid-file }}
        sleep ${{ inputs.startup-wait-seconds }}

        # Check if backend started successfully
        if ! kill -0 $(cat ${{ inputs.pid-file }}) 2>/dev/null; then
          echo "Backend failed to start. Log:"
          cat ${{ inputs.log-file }}
          exit 1
        fi
        echo "Backend started with PID $(cat ${{ inputs.pid-file }})"
